pub mod add_alarm;
pub mod confirm_dialog;
pub mod icons;
pub mod alarms;
pub mod colors;
pub mod devices;
pub mod edit_profile;
pub mod login;
pub mod navbar;
pub mod notifications;
pub mod play_alarm;
pub mod qr_scanner;
pub mod register;
pub mod settings;
pub mod user_menu;
pub mod welcome;

pub use add_alarm::add_alarm_dialog;
pub use confirm_dialog::confirm_dialog;
pub use icons::{icon_el, icon_svg, Icon};
pub use alarms::alarms_view;
pub use colors::colors_dialog;
pub use devices::{devices_view, edit_device_dialog};
pub use edit_profile::edit_profile_dialog;
pub use login::login_form;
pub use navbar::navbar;
pub use notifications::notifications_view;
pub use play_alarm::play_alarm_view;
pub use qr_scanner::qr_scanner;
pub use register::register_form;
pub use settings::settings_dialog;
pub use user_menu::user_menu_view;
pub use welcome::welcome_view;
